import './Users.css';
import { DataGrid, Column } from 'devextreme-react/data-grid';

const Users = () => {
  const employees = [
    {
      Id: 0,
      FirstName: 'Georgi',
      LastName: 'Ivanov',
      UserName: 'rammer17',
      Age: 19,
      Email: 'rammer17@abv.bg',
      IsVerified: true,
      Role: 'Moderator',
      Balance: 2351.31,
    },
    {
      Id: 0,
      FirstName: 'Georgi',
      LastName: 'Ivanov',
      UserName: 'rammer17',
      Age: 19,
      Email: 'rammer17@abv.bg',
      IsVerified: true,
      Role: 'Moderator',
      Balance: 2351.31,
    },
    {
      Id: 0,
      FirstName: 'Georgi',
      LastName: 'Ivanov',
      UserName: 'rammer17',
      Age: 19,
      Email: 'rammer17@abv.bg',
      IsVerified: true,
      Role: 'Moderator',
      Balance: 2351.31,
    },
    {
      Id: 0,
      FirstName: 'Georgi',
      LastName: 'Ivanov',
      UserName: 'rammer17',
      Age: 19,
      Email: 'rammer17@abv.bg',
      IsVerified: true,
      Role: 'Moderator',
      Balance: 2351.31,
    },
    {
      Id: 0,
      FirstName: 'Georgi',
      LastName: 'Ivanov',
      UserName: 'rammer17',
      Age: 19,
      Email: 'rammer17@abv.bg',
      IsVerified: true,
      Role: 'Moderator',
      Balance: 2351.31,
    },
    {
      Id: 0,
      FirstName: 'Georgi',
      LastName: 'Ivanov',
      UserName: 'rammer17',
      Age: 19,
      Email: 'rammer17@abv.bg',
      IsVerified: true,
      Role: 'Moderator',
      Balance: 2351.31,
    },
    {
      Id: 0,
      FirstName: 'Georgi',
      LastName: 'Ivanov',
      UserName: 'rammer17',
      Age: 19,
      Email: 'rammer17@abv.bg',
      IsVerified: true,
      Role: 'Moderator',
      Balance: 2351.31,
    },
    {
      Id: 0,
      FirstName: 'Georgi',
      LastName: 'Ivanov',
      UserName: 'rammer17',
      Age: 19,
      Email: 'rammer17@abv.bg',
      IsVerified: true,
      Role: 'Moderator',
      Balance: 2351.31,
    },
    {
      Id: 0,
      FirstName: 'Georgi',
      LastName: 'Ivanov',
      UserName: 'rammer17',
      Age: 19,
      Email: 'rammer17@abv.bg',
      IsVerified: true,
      Role: 'Moderator',
      Balance: 2351.31,
    },
    {
      Id: 0,
      FirstName: 'Georgi',
      LastName: 'Ivanov',
      UserName: 'rammer17',
      Age: 19,
      Email: 'rammer17@abv.bg',
      IsVerified: true,
      Role: 'Moderator',
      Balance: 2351.31,
    },
    {
      Id: 0,
      FirstName: 'Georgi',
      LastName: 'Ivanov',
      UserName: 'rammer17',
      Age: 19,
      Email: 'rammer17@abv.bg',
      IsVerified: true,
      Role: 'Moderator',
      Balance: 2351.31,
    },
    {
      Id: 0,
      FirstName: 'Georgi',
      LastName: 'Ivanov',
      UserName: 'rammer17',
      Age: 19,
      Email: 'rammer17@abv.bg',
      IsVerified: true,
      Role: 'Moderator',
      Balance: 2351.31,
    },
    {
      Id: 0,
      FirstName: 'Georgi',
      LastName: 'Ivanov',
      UserName: 'rammer17',
      Age: 19,
      Email: 'rammer17@abv.bg',
      IsVerified: true,
      Role: 'Moderator',
      Balance: 2351.31,
    },
    {
      Id: 0,
      FirstName: 'Georgi',
      LastName: 'Ivanov',
      UserName: 'rammer17',
      Age: 19,
      Email: 'rammer17@abv.bg',
      IsVerified: true,
      Role: 'Moderator',
      Balance: 2351.31,
    },
    {
      Id: 0,
      FirstName: 'Georgi',
      LastName: 'Ivanov',
      UserName: 'rammer17',
      Age: 19,
      Email: 'rammer17@abv.bg',
      IsVerified: true,
      Role: 'Moderator',
      Balance: 2351.31,
    },
    {
      Id: 0,
      FirstName: 'Georgi',
      LastName: 'Ivanov',
      UserName: 'rammer17',
      Age: 19,
      Email: 'rammer17@abv.bg',
      IsVerified: true,
      Role: 'Moderator',
      Balance: 2351.31,
    },
    {
      Id: 0,
      FirstName: 'Georgi',
      LastName: 'Ivanov',
      UserName: 'rammer17',
      Age: 19,
      Email: 'rammer17@abv.bg',
      IsVerified: true,
      Role: 'Moderator',
      Balance: 2351.31,
    },
    {
      Id: 0,
      FirstName: 'Georgi',
      LastName: 'Ivanov',
      UserName: 'rammer17',
      Age: 19,
      Email: 'rammer17@abv.bg',
      IsVerified: true,
      Role: 'Moderator',
      Balance: 2351.31,
    },
    {
      Id: 0,
      FirstName: 'Georgi',
      LastName: 'Ivanov',
      UserName: 'rammer17',
      Age: 19,
      Email: 'rammer17@abv.bg',
      IsVerified: true,
      Role: 'Moderator',
      Balance: 2351.31,
    },
    {
      Id: 0,
      FirstName: 'Georgi',
      LastName: 'Ivanov',
      UserName: 'rammer17',
      Age: 19,
      Email: 'rammer17@abv.bg',
      IsVerified: true,
      Role: 'Moderator',
      Balance: 2351.31,
    },
    {
      Id: 0,
      FirstName: 'Georgi',
      LastName: 'Ivanov',
      UserName: 'rammer17',
      Age: 19,
      Email: 'rammer17@abv.bg',
      IsVerified: true,
      Role: 'Moderator',
      Balance: 2351.31,
    },
    {
      Id: 0,
      FirstName: 'Georgi',
      LastName: 'Ivanov',
      UserName: 'rammer17',
      Age: 19,
      Email: 'rammer17@abv.bg',
      IsVerified: true,
      Role: 'Moderator',
      Balance: 2351.31,
    },
  ];

  return (
    <div className="data-wrapper">
      <DataGrid dataSource={employees}>
        <Column dataField="Id" dataType="number" width={150}></Column>
        <Column dataField="FirstName" dataType="text" width={200}></Column>
        <Column dataField="LastName" dataType="text" width={200}></Column>
        <Column dataField="UserName" dataType="text" width={200}></Column>
        <Column dataField="Age" dataType="number" width={150}></Column>
        <Column dataField="Email" dataType="text" width={300}></Column>
        <Column dataField="IsVerified" dataType="boolean" width={150}></Column>
        <Column dataField="Role" dataType="text" width={200}></Column>
        <Column dataField="Balance" dataType="number" width={200}></Column>
      </DataGrid>
    </div>
  );
};

export default Users;
